repos:
  - repo: https://github.com/ElijahHoff/arbitrary_style_transfer/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/ElijahHoff/arbitrary_style_transfer/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
  - repo: https://github.com/ElijahHoff/arbitrary_style_transfer/isort
    rev: 5.12.0
    hooks:
      - id: isort
